add_executable(test_lect_database_cpp
    test_lect_database.cpp
)
target_link_libraries(test_lect_database_cpp PRIVATE lect_database_core)
add_test(NAME test_lect_database_cpp COMMAND test_lect_database_cpp)

add_executable(test_lect_database_header_surface_cpp
    header_surface/main.cpp
    header_surface/lect_database_header.cpp
)
target_link_libraries(test_lect_database_header_surface_cpp PRIVATE lect_database_core)
add_test(NAME test_lect_database_header_surface_cpp COMMAND test_lect_database_header_surface_cpp)

add_executable(test_sbf_adapter_cpp
    test_sbf_adapter.cpp
)
target_link_libraries(test_sbf_adapter_cpp PRIVATE lect_database_sbf_adapter)
add_test(NAME test_sbf_adapter_cpp COMMAND test_sbf_adapter_cpp)