#include "leaf_sweep_grower_diagnostics.h"

#include <SBF/runtime.h>

#include "leaf_sweep_grower_internal.h"

namespace rbf {

void record_leaf_sweep_worker_oracle_counters(LeafSweepResult& result,
											  StageContext& context,
											  const OracleCounters& counters) {
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.node_validations",
				static_cast<double>(counters.node_validations));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_reused_external_evidence",
				static_cast<double>(counters.materialization_reused_external_evidence));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_exact_hits",
				static_cast<double>(counters.materialization_external_exact_hits));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_exact_misses",
				static_cast<double>(counters.materialization_external_exact_misses));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_live_fallbacks",
				static_cast<double>(counters.materialization_external_live_fallbacks));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_maybe_live_retries",
				static_cast<double>(counters.materialization_external_maybe_live_retries));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_maybe_live_retry_free",
				static_cast<double>(counters.materialization_external_maybe_live_retry_free));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.interval_replay_compatibility_checks",
				static_cast<double>(counters.interval_replay_compatibility_checks));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.interval_replay_compatible",
				static_cast<double>(counters.interval_replay_compatible));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.interval_replay_incompatible",
				static_cast<double>(counters.interval_replay_incompatible));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.interval_replay_direct_exact_hits",
				static_cast<double>(counters.interval_replay_direct_exact_hits));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.interval_replay_key_only_blocked",
				static_cast<double>(counters.interval_replay_key_only_blocked));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.canonical_frame_invalid",
				static_cast<double>(counters.canonical_frame_invalid));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.canonical_reflected_seed_misses",
				static_cast<double>(counters.canonical_reflected_seed_misses));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.validate_node_total_time_us",
				counters.validate_node_total_time_us);
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_external_lookup_time_us",
				counters.materialization_external_lookup_time_us);
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_envelope_compute_time_us",
				counters.materialization_envelope_compute_time_us);
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.materialization_envelope_collision_time_us",
				counters.materialization_envelope_collision_time_us);
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_queries",
				static_cast<double>(counters.envelope_collision_queries));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_free",
				static_cast<double>(counters.envelope_collision_free));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_maybe",
				static_cast<double>(counters.envelope_collision_maybe));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_envelope_aabb_tests",
				static_cast<double>(counters.envelope_collision_envelope_aabb_tests));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_envelope_aabb_rejects",
				static_cast<double>(counters.envelope_collision_envelope_aabb_rejects));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_link_union_aabb_tests",
				static_cast<double>(counters.envelope_collision_link_union_aabb_tests));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_link_union_aabb_rejects",
				static_cast<double>(counters.envelope_collision_link_union_aabb_rejects));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_link_aabb_tests",
				static_cast<double>(counters.envelope_collision_link_aabb_tests));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_link_aabb_rejects",
				static_cast<double>(counters.envelope_collision_link_aabb_rejects));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_kdop_tests",
				static_cast<double>(counters.envelope_collision_kdop_tests));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_kdop_rejects",
				static_cast<double>(counters.envelope_collision_kdop_rejects));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_gjk_tests",
				static_cast<double>(counters.envelope_collision_gjk_tests));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_gjk_rejects",
				static_cast<double>(counters.envelope_collision_gjk_rejects));
	add_counter(result,
				context,
				"leaf_sweep.worker_oracle.envelope_collision_gjk_iterations",
				static_cast<double>(counters.envelope_collision_gjk_iterations));
}

}  // namespace rbf
