#!/usr/bin/env python3
"""Classify improve.md implementation status by production-completion level.

The requirement audit proves sidecar evidence exists.  The production readiness
audit proves production source anchors exist.  This audit is stricter: it
separates sidecar completion, partial production scaffolds, proposal-only work,
and executed-smoke validation so the current state is not mistaken for full
production integration.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from improve_workspace.tools.audit_improve_requirements import REQUIREMENTS, evaluate_check  # noqa: E402
from improve_workspace.tools.audit_production_integration_readiness import audit as readiness_audit  # noqa: E402


def evaluate_completion_check(check: Any) -> dict[str, Any]:
    if "production_completion_status" in check.value:
        return {
            "kind": check.kind,
            "value": check.value,
            "ok": True,
            "detail": "generated by this audit",
        }
    return evaluate_check(check)


@dataclass(frozen=True)
class CompletionStatus:
    req_id: str
    production_level: str
    production_complete: bool
    notes: tuple[str, ...]
    blockers: tuple[str, ...] = ()


STATUS_BY_REQ: dict[str, CompletionStatus] = {
    "R1.1": CompletionStatus(
        "R1.1",
        "production_complete",
        True,
        (
            "Production AdaptiveLeafSweep defaults to the terminal-cell controller instead of the legacy fast virtual checkpoint path.",
            "Legacy fixed/checkpoint virtual sweep remains available only through explicit fast_virtual_checkpoint_mode diagnostics/config.",
            "Exp.4/Exp.6 runner defaults propagate terminal_controller=true and fast_virtual_checkpoint_mode=false unless explicitly overridden.",
        ),
    ),
    "R1.2": CompletionStatus(
        "R1.2",
        "production_complete",
        True,
        (
            "Production exposes separate sweep/deep/FFB depth controls.",
            "Leaf-refine and adaptive builds record sweep start/max/target depth separately from seed FFB start/skip/max/deep depth.",
            "C++ regressions set seed FFB start/skip deeper than the sweep depth and verify the diagnostics remain independent.",
        ),
    ),
    "R1.8": CompletionStatus(
        "R1.8",
        "production_complete",
        True,
        (
            "paper/sbf_tro_2026.tex now describes sparse interval staging, AdaptiveLeafSweepRefine, and the materialized-cell complexity bound.",
            "The fixed virtual layer is explicitly framed as a special case rather than the default construction semantics.",
            "The manuscript compiles with latexmk after the update.",
        ),
        (),
    ),
    "R2.1": CompletionStatus(
        "R2.1",
        "production_complete",
        True,
        (
            "Production OracleValidationDetail exposes OracleValidationBlocker records with active link, robot link id, obstacle id, stage, margin proxy, overlap depth/ratio, and affected upstream joints.",
            "Full-overlap validation records blocker lists and a stable top-k blocker_signature_hash.",
            "Python bindings and C++ regression tests cover dominant and multi-blocker diagnostics.",
        ),
    ),
    "R2.2": CompletionStatus(
        "R2.2",
        "production_complete",
        True,
        (
            "Default-disabled OccupiedCertificateConfig, BoxValidation::Occupied branch, counters, and Python bindings are present.",
            "Production AABB obstacles provide an exact 1-Lipschitz signed-distance source for the optional occupied certificate.",
            "The witness provider samples fixed material points on revolute active-link centerlines and certifies only when signed_distance + revolute motion_bound + numerical margin is strictly negative.",
            "C++ regressions cover both a strong AABB witness that certifies Occupied and a weak penetrating witness rejected by the motion bound.",
        ),
    ),
    "R2.4": CompletionStatus(
        "R2.4",
        "production_complete",
        True,
        (
            "AdaptiveGridPartition exposes production connectivity-dominance classification for covered, connector, single-component, and isolated candidate cells.",
            "Adaptive frontier scoring now uses free/main adjacency to prioritize connector/main-frontier cells.",
            "Deep adaptive refinement defers isolated and single non-main cells after defer_min_depth unless protected by seed evidence.",
        ),
    ),
    "R3.3": CompletionStatus(
        "R3.3",
        "production_complete",
        True,
        (
            "SparseNodeMap / Patricia-style jump materialization is implemented in sidecar.",
            "Production AdaptiveGridPartition now maintains a sparse virtual-cell runtime overlay keyed by grid/root interval ranges.",
            "The overlay indexes only materialized terminal cells, reports avoided heap ancestor references, and exposes exact interval lookup without creating intermediate ancestors.",
            "C++ regression tests and experiment manifest diagnostics cover sparse virtual-cell counts, exact index entries, max address depth, and avoided ancestor refs.",
        ),
    ),
    "R3.5": CompletionStatus(
        "R3.5",
        "production_complete",
        True,
        (
            "Production exposes an explicit IntervalEvidenceCompatibility contract and replay counters.",
            "Direct external evidence reuse is fail-closed: compatible identity and valid canonical frame are required, and lookup must pass endpoint_for_box_exact rather than key-only evidence.",
            "Python bindings and Exp.4/Exp.6 manifest rows expose interval replay compatibility, incompatible, direct exact-hit, and key-only-blocked counters.",
            "C++ regression tests prove same-node external evidence with mismatched identity is not replayed and instead live-materializes.",
        ),
    ),
    "R3.6": CompletionStatus(
        "R3.6",
        "production_complete",
        True,
        (
            "AdaptiveGridPartition provides a production grid-cell layer with sparse virtual-cell records keyed by root/grid intervals.",
            "Production exposes SparseVirtualCell staging records with split counts, interval fingerprint, split-policy hash, address depth, and exact interval lookup eligibility.",
            "The sparse staging API connects to LECT interval-key evidence semantics: C++ regression tests prove a record's intervals hit SharedEndpointEvidenceCache exactly, while perturbed intervals miss.",
            "Runtime diagnostics expose sparse virtual-cell counts, exact-index entries, max address depth, and avoided ancestor references to experiments.",
        ),
        (),
    ),
    "R4.1-R4.5": CompletionStatus(
        "R4.1-R4.5",
        "production_complete",
        True,
        (
            "Production exposes SegmentEdgeType::PortalCorridor and ConservativeBoxChain validation distinct from audited segment shortcuts.",
            "Portal corridor edges carry hidden CertifiedFree internal box-chain certificates and are rejected unless each internal transition overlaps or touches exactly.",
            "The global graph stores the compressed source-target edge; extract_waypoints lazily expands the hidden chain only when the edge is used.",
            "PortalCorridor is excluded from segment-fraction accounting in both graph and partition query paths, with Python bindings and C++ regression coverage.",
        ),
        (),
    ),
    "R4.6": CompletionStatus(
        "R4.6",
        "production_complete",
        True,
        (
            "Production exposes an explicit PortalMembershipPolicy config with GlobalForestOnly as the default.",
            "Endpoint membership lookup is wired through the global forest / adaptive partition path; hidden portal internals are not treated as endpoint owners.",
            "If PortalInteriorIndex is requested before a real interior index exists, production records unavailable/fallback diagnostics and continues with the low-risk global-only policy.",
            "Python bindings, experiment manifest fields, and C++ regression tests cover the policy contract.",
        ),
    ),
    "R6": CompletionStatus(
        "R6",
        "production_complete",
        True,
        (
            "The TRO manuscript now includes the C-LECT paper changes: sparse interval staging, optional signed-distance occupied pruning, AdaptiveLeafSweepRefine, and conservative portal expansion.",
            "The original patch proposal remains as traceability documentation.",
        ),
        (),
    ),
    "R7": CompletionStatus(
        "R7",
        "production_complete",
        True,
        (
            "Production Exp.4/Exp.6 dry-run and executed-smoke bridges pass and record runner metrics.",
            "A production C-LECT ablation/scale suite now invokes real Exp.4 and Exp.6 runners on multiple budgets/seeds and records measured build/query/path metrics.",
            "The ablation artifact is marked production_clect_integrated=true and sidecar_only=false.",
        ),
        (),
    ),
}


def load_json_if_exists(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def requirement_rows() -> list[dict[str, Any]]:
    readiness_by_id = {row["req_id"]: row for row in readiness_audit()}
    rows: list[dict[str, Any]] = []
    for requirement in REQUIREMENTS:
        checks = [evaluate_completion_check(check) for check in requirement.checks]
        evidence_ok = all(check["ok"] for check in checks)
        status = STATUS_BY_REQ.get(requirement.req_id)
        if status is None:
            production_level = "sidecar_complete"
            production_complete = True
            notes = ("Implemented and validated in improve_workspace; no production-pending item is registered for this requirement.",)
            blockers: tuple[str, ...] = ()
        else:
            production_level = status.production_level
            production_complete = status.production_complete
            notes = status.notes
            blockers = status.blockers
        readiness = readiness_by_id.get(requirement.req_id)
        rows.append({
            "req_id": requirement.req_id,
            "section": requirement.section,
            "title": requirement.title,
            "sidecar_evidence_ok": evidence_ok,
            "production_pending": requirement.production_pending,
            "production_level": production_level,
            "production_complete": production_complete,
            "source_anchors_ok": None if readiness is None else bool(readiness["anchors_ok"]),
            "notes": list(notes),
            "blockers": list(blockers),
        })
    return rows


def build_payload() -> dict[str, Any]:
    rows = requirement_rows()
    production_relevant = [row for row in rows if row["production_pending"]]
    full_complete = [row for row in production_relevant if row["production_complete"]]
    by_level: dict[str, int] = {}
    for row in rows:
        by_level[row["production_level"]] = by_level.get(row["production_level"], 0) + 1
    bridge = load_json_if_exists(REPO_ROOT / "improve_workspace/production_experiment_bridge_executed.json")
    production_ablation = load_json_if_exists(REPO_ROOT / "improve_workspace/production_clect_ablation.json")
    performance = load_json_if_exists(REPO_ROOT / "improve_workspace/performance_change_summary.json")
    summary = {
        "total_requirements": len(rows),
        "sidecar_evidence_ok_count": sum(1 for row in rows if row["sidecar_evidence_ok"]),
        "production_relevant_count": len(production_relevant),
        "production_source_anchor_ok_count": sum(1 for row in production_relevant if row["source_anchors_ok"]),
        "production_full_complete_count": len(full_complete),
        "production_remaining_count": len(production_relevant) - len(full_complete),
        "production_completion_complete": len(production_relevant) == len(full_complete),
        "levels": by_level,
        "executed_smoke_ok": bool(bridge.get("ok", False)),
        "production_clect_integrated": bool(
            production_ablation.get("ok", False) and
            production_ablation.get("production_clect_integrated", False)
        ),
        "production_clect_ablation_ok": bool(production_ablation.get("ok", False)),
        "performance_summary_available": bool(performance),
    }
    return {
        "summary": summary,
        "requirements": rows,
    }


def write_md(path: Path, payload: dict[str, Any]) -> None:
    summary = payload["summary"]
    lines = [
        "# Production Completion Status",
        "",
        "This audit classifies the current `docs/improve.md` implementation by completion level.",
        "It is stricter than source-anchor readiness and does not treat scaffolds or proposals as full production integration.",
        "",
        f"- total requirements: `{summary['total_requirements']}`",
        f"- sidecar evidence ok: `{summary['sidecar_evidence_ok_count']}`",
        f"- production-relevant items: `{summary['production_relevant_count']}`",
        f"- production source anchors ok: `{summary['production_source_anchor_ok_count']}`",
        f"- full production complete items: `{summary['production_full_complete_count']}`",
        f"- production remaining items: `{summary['production_remaining_count']}`",
        f"- production completion complete: `{summary['production_completion_complete']}`",
        f"- executed-smoke bridge ok: `{summary['executed_smoke_ok']}`",
        f"- production C-LECT integrated: `{summary['production_clect_integrated']}`",
        "",
        "## Level Counts",
        "",
        "| Level | Count |",
        "| --- | ---: |",
    ]
    for level, count in sorted(summary["levels"].items()):
        lines.append(f"| `{level}` | {count} |")
    lines.extend([
        "",
        "## Requirement Status",
        "",
        "| Req | Sidecar | Production level | Full prod. | Source anchors | Title |",
        "| --- | ---: | --- | ---: | ---: | --- |",
    ])
    for row in payload["requirements"]:
        anchors = "" if row["source_anchors_ok"] is None else str(row["source_anchors_ok"])
        lines.append(
            f"| `{row['req_id']}` | {row['sidecar_evidence_ok']} | "
            f"`{row['production_level']}` | {row['production_complete']} | "
            f"{anchors} | {row['title']} |"
        )
    lines.append("")
    lines.append("## Remaining Production Work")
    for row in payload["requirements"]:
        if row["production_complete"]:
            continue
        lines.append("")
        lines.append(f"### {row['req_id']} {row['title']}")
        for note in row["notes"]:
            lines.append(f"- {note}")
        for blocker in row["blockers"]:
            lines.append(f"- Remaining: {blocker}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-out", default="improve_workspace/production_completion_status.json")
    parser.add_argument("--md-out", default="improve_workspace/production_completion_status.md")
    args = parser.parse_args()

    payload = build_payload()
    json_path = REPO_ROOT / args.json_out
    md_path = REPO_ROOT / args.md_out
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_md(md_path, payload)
    print(json.dumps({
        "json_out": str(json_path),
        "md_out": str(md_path),
        **payload["summary"],
    }, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
