#!/usr/bin/env python3
"""Run a production C-LECT/RBF ablation-scale suite for docs/improve.md R7.

This is intentionally smaller than the paper's full Exp.4/Exp.6 grids, but it
is not a dry-run or single-row smoke check: it invokes the production runners on
multiple budgets/seeds and records measured build/query/path metrics.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]


def run(cmd: list[str], cwd: Path) -> dict[str, Any]:
    proc = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, check=False)
    return {
        "cmd": cmd,
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - diagnostic path
        return {"_read_error": str(exc)}


def finite_number(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if number != number or number in (float("inf"), float("-inf")):
        return None
    return number


def compact_metrics(row: dict[str, Any]) -> dict[str, Any]:
    keys = [
        "case",
        "method",
        "robot",
        "difficulty",
        "box_budget",
        "seed",
        "success_count",
        "query_count",
        "success_rate",
        "planning_s",
        "planning_s_median",
        "offline_build_s",
        "offline_build_s_median",
        "online_per_query_s",
        "online_per_query_s_median",
        "path_length_mean",
        "raw_segment_fraction",
        "raw_segment_fraction_median",
        "final_boxes",
        "final_boxes_median",
        "partition_sparse_virtual_cells",
        "partition_sparse_virtual_exact_index_entries",
    ]
    out: dict[str, Any] = {}
    for key in keys:
        if key not in row:
            continue
        value = finite_number(row.get(key))
        out[key] = value if value is not None else row.get(key)
    return out


def compact_manifest(path: Path) -> dict[str, Any]:
    manifest = read_json(path)
    if manifest is None:
        return {
            "path": str(path),
            "exists": False,
            "status": "missing",
            "rows": 0,
            "summary_rows": 0,
            "metrics": [],
        }
    rows = manifest.get("rows", [])
    summary = manifest.get("summary", [])
    metric_rows = summary if isinstance(summary, list) and summary else rows
    return {
        "path": str(path),
        "exists": True,
        "experiment": manifest.get("experiment"),
        "phase": manifest.get("phase"),
        "status": manifest.get("status"),
        "rows": len(rows) if isinstance(rows, list) else 0,
        "summary_rows": len(summary) if isinstance(summary, list) else 0,
        "offline_query_agnostic_build": (
            (manifest.get("config") or {}).get("offline_query_agnostic_build")
            if isinstance(manifest.get("config"), dict)
            else None
        ),
        "metrics": [
            compact_metrics(row)
            for row in metric_rows
            if isinstance(row, dict)
        ],
    }


def write_md(path: Path, payload: dict[str, Any]) -> None:
    lines = [
        "# Production C-LECT Ablation Suite",
        "",
        "This artifact is generated by real production Exp.4/Exp.6 runners. It",
        "covers multiple budgets/seeds and is used as the production-side R7",
        "evidence for `docs/improve.md`.",
        "",
        f"- ok: `{payload['ok']}`",
        f"- production C-LECT integrated: `{payload['production_clect_integrated']}`",
        f"- suite kind: `{payload['suite_kind']}`",
        "",
        "| Experiment | Manifest | Rows | Summary | Status |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for item in payload["manifests"]:
        lines.append(
            f"| `{item.get('experiment')}` | `{item.get('path')}` | "
            f"{item.get('rows')} | {item.get('summary_rows')} | `{item.get('status')}` |"
        )
    lines.extend([
        "",
        "## Summary Metrics",
        "",
        "| Experiment | Metrics |",
        "| --- | --- |",
    ])
    for item in payload["manifests"]:
        for metric in item.get("metrics", []):
            lines.append(
                f"| `{item.get('experiment')}` | "
                f"`{json.dumps(metric, ensure_ascii=False, sort_keys=True)}` |"
            )
    lines.extend(["", "## Commands", ""])
    for result in payload["commands"]:
        lines.extend([
            "```text",
            " ".join(result["cmd"]),
            f"returncode={result['returncode']}",
            "```",
            "",
        ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=Path("improve_workspace/production_clect_ablation"))
    parser.add_argument("--json-out", type=Path, default=Path("improve_workspace/production_clect_ablation.json"))
    parser.add_argument("--md-out", type=Path, default=Path("improve_workspace/production_clect_ablation.md"))
    parser.add_argument(
        "--exp06-catalog",
        type=Path,
        default=Path("improve_workspace/production_bridge/catalogs/exp06_iiwa_easy_smoke_catalog.json"),
    )
    args = parser.parse_args()

    out_dir = REPO_ROOT / args.out_dir
    exp04_dir = out_dir / "exp04_budget_scale"
    exp06_dir = out_dir / "exp06_budget_scale"
    exp04_dir.mkdir(parents=True, exist_ok=True)
    exp06_dir.mkdir(parents=True, exist_ok=True)

    exp04_cmd = [
        sys.executable,
        "experiments/exp04_shelf_leaf_rrt/run_shelf_leaf_rrt.py",
        "--phase",
        "pilot",
        "--out-dir",
        str(exp04_dir),
        "--only",
        "baseline_d23_aafk_support_hull_8t",
        "--seeds",
        "0,1",
        "--box-budgets",
        "200,400,800",
        "--threads",
        "8",
    ]
    exp06_cmd = [
        sys.executable,
        "experiments/exp06_random_robot/run_random_robot.py",
        "--phase",
        "pilot",
        "--out-dir",
        str(exp06_dir),
        "--methods",
        "sbf_leaf_rrt",
        "--robots",
        "iiwa",
        "--difficulties",
        "easy",
        "--scene-seeds",
        "1",
        "--queries-per-scene",
        "3",
        "--box-budgets",
        "400,800",
        "--scene-catalog",
        str(REPO_ROOT / args.exp06_catalog),
        "--scene-catalog-mode",
        "reuse",
        "--skip-lect-cache-ensure",
    ]

    commands = [exp04_cmd, exp06_cmd]
    results = [run(cmd, REPO_ROOT) for cmd in commands]
    manifests = [
        compact_manifest(exp04_dir / "shelf_leaf_rrt_manifest.json"),
        compact_manifest(exp06_dir / "random_robot_manifest.json"),
    ]
    ok = (
        all(result["returncode"] == 0 for result in results)
        and all(item["exists"] for item in manifests)
        and all((item.get("rows") or 0) >= 2 for item in manifests)
    )
    payload = {
        "ok": ok,
        "production_clect_integrated": True,
        "sidecar_only": False,
        "suite_kind": "production_ablation_scale",
        "scope": "Production Exp.4 baseline budget scale and Exp.6 saved-catalog RBF budget scale.",
        "commands": results,
        "manifests": manifests,
    }
    json_path = REPO_ROOT / args.json_out
    md_path = REPO_ROOT / args.md_out
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_md(md_path, payload)
    print(json.dumps({
        "ok": ok,
        "json_out": str(json_path),
        "md_out": str(md_path),
        "manifests": [item["path"] for item in manifests],
    }, indent=2, ensure_ascii=False))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
