#pragma once

#include <SBF/sbf.h>

#include "binding_utils.h"

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <limits>
#include <string>
#include <vector>

namespace py = pybind11;

namespace rbf::python_binding {

inline void register_planning_option_types(py::module_& module) {
    py::class_<rbf::BestTightenOptions>(module, "BestTightenOptions")
        .def(py::init<>())
        .def_readwrite("depth_synchronous", &rbf::BestTightenOptions::depth_synchronous)
        .def_readwrite("prefer_sector_boundary", &rbf::BestTightenOptions::prefer_sector_boundary)
        .def_readwrite("use_minimax", &rbf::BestTightenOptions::use_minimax)
        .def_readwrite("max_candidate_dim", &rbf::BestTightenOptions::max_candidate_dim)
        .def_readwrite("min_candidate_width", &rbf::BestTightenOptions::min_candidate_width)
        .def_readwrite("width_penalty", &rbf::BestTightenOptions::width_penalty)
        .def_readwrite("shape_balancing", &rbf::BestTightenOptions::shape_balancing)
        .def_readwrite("max_child_aspect", &rbf::BestTightenOptions::max_child_aspect)
        .def_readwrite("min_split_width_fraction", &rbf::BestTightenOptions::min_split_width_fraction)
        .def_readwrite("shape_weight", &rbf::BestTightenOptions::shape_weight)
        .def_readwrite("balance_weight", &rbf::BestTightenOptions::balance_weight)
        .def_readwrite("relative_gain_weight", &rbf::BestTightenOptions::relative_gain_weight)
        .def_readwrite("widest_tiebreak_weight", &rbf::BestTightenOptions::widest_tiebreak_weight)
        .def_readwrite("recent_dim_cooling", &rbf::BestTightenOptions::recent_dim_cooling)
        .def_readwrite("recent_dim_window", &rbf::BestTightenOptions::recent_dim_window)
        .def_readwrite("recent_dim_weight", &rbf::BestTightenOptions::recent_dim_weight)
        .def_readwrite("recent_dim_shape_aspect_trigger", &rbf::BestTightenOptions::recent_dim_shape_aspect_trigger)
        .def_readwrite("dim_mask", &rbf::BestTightenOptions::dim_mask)
        .def_readwrite("dim_priority_weights", &rbf::BestTightenOptions::dim_priority_weights)
        .def_readwrite("dim_priority_weight", &rbf::BestTightenOptions::dim_priority_weight);
    py::class_<rbf::OracleSplitOptions>(module, "OracleSplitOptions")
        .def(py::init<>())
        .def_readwrite("use_best_tighten", &rbf::OracleSplitOptions::use_best_tighten)
        .def_readwrite("best_tighten", &rbf::OracleSplitOptions::best_tighten);

    py::class_<rbf::OccupiedCertificateConfig>(module, "OccupiedCertificateConfig")
        .def(py::init<>())
        .def_readwrite("enabled", &rbf::OccupiedCertificateConfig::enabled)
        .def_readwrite("numerical_epsilon", &rbf::OccupiedCertificateConfig::numerical_epsilon)
        .def_readwrite("min_penetration_margin", &rbf::OccupiedCertificateConfig::min_penetration_margin);

    py::class_<rbf::OracleValidationConfig>(module, "OracleValidationConfig")
        .def(py::init<>())
        .def_readwrite("mode", &rbf::OracleValidationConfig::mode)
        .def_readwrite("accept_unsafe_free", &rbf::OracleValidationConfig::accept_unsafe_free)
        .def_readwrite("enable_validation_cache", &rbf::OracleValidationConfig::enable_validation_cache)
        .def_readwrite("validation_cache_max_entries", &rbf::OracleValidationConfig::validation_cache_max_entries)
        .def_readwrite("enable_endpoint_evidence_cache", &rbf::OracleValidationConfig::enable_endpoint_evidence_cache)
        .def_readwrite("store_endpoint_evidence_cache", &rbf::OracleValidationConfig::store_endpoint_evidence_cache)
        .def_readwrite("endpoint_cache_min_effective_width", &rbf::OracleValidationConfig::endpoint_cache_min_effective_width)
        .def_readwrite("external_evidence_materialization", &rbf::OracleValidationConfig::external_evidence_materialization)
        .def_readwrite("external_evidence_scoring", &rbf::OracleValidationConfig::external_evidence_scoring)
        .def_readwrite("external_evidence_backfill_active", &rbf::OracleValidationConfig::external_evidence_backfill_active)
        .def_readwrite("external_evidence_live_retry_on_maybe", &rbf::OracleValidationConfig::external_evidence_live_retry_on_maybe)
        .def_readwrite("stateless_materialization_context", &rbf::OracleValidationConfig::stateless_materialization_context)
        .def_readwrite("enable_worker_shared_endpoint_cache", &rbf::OracleValidationConfig::enable_worker_shared_endpoint_cache)
        .def_readwrite("shared_endpoint_cache_max_entries", &rbf::OracleValidationConfig::shared_endpoint_cache_max_entries)
        .def_readwrite("shared_endpoint_cache_max_bytes", &rbf::OracleValidationConfig::shared_endpoint_cache_max_bytes)
        .def_readwrite("collect_full_overlap_stats", &rbf::OracleValidationConfig::collect_full_overlap_stats)
        .def_readwrite("occupied_certificate", &rbf::OracleValidationConfig::occupied_certificate);

    py::enum_<rbf::FindFreeBoxSearchMode>(module, "FindFreeBoxSearchMode")
        .value("Linear", rbf::FindFreeBoxSearchMode::Linear)
        .value("BinaryDepth", rbf::FindFreeBoxSearchMode::BinaryDepth);

    py::class_<rbf::FindFreeBoxOptions>(module, "FindFreeBoxOptions")
        .def(py::init<>())
        .def_readwrite("max_depth", &rbf::FindFreeBoxOptions::max_depth)
        .def_readwrite("start_depth", &rbf::FindFreeBoxOptions::start_depth)
        .def_readwrite("skip_to_depth", &rbf::FindFreeBoxOptions::skip_to_depth)
        .def_readwrite("search_mode", &rbf::FindFreeBoxOptions::search_mode)
        .def_readwrite("binary_probe_depth", &rbf::FindFreeBoxOptions::binary_probe_depth)
        .def_readwrite("adaptive_depths", &rbf::FindFreeBoxOptions::adaptive_depths)
        .def_readwrite("deadline_ms", &rbf::FindFreeBoxOptions::deadline_ms)
        .def_readwrite("split_reserved_leaf", &rbf::FindFreeBoxOptions::split_reserved_leaf)
        .def_readwrite("split_unknown_leaf", &rbf::FindFreeBoxOptions::split_unknown_leaf)
        .def_readwrite("reject_seed_collision", &rbf::FindFreeBoxOptions::reject_seed_collision)
        .def_readwrite("skip_existing_cover_check", &rbf::FindFreeBoxOptions::skip_existing_cover_check)
        .def_readwrite("split", &rbf::FindFreeBoxOptions::split);

    py::class_<rbf::GrowerConfig::DepthStage>(module, "GrowerDepthStage")
        .def(py::init<>())
        .def_readwrite("box_limit", &rbf::GrowerConfig::DepthStage::box_limit)
        .def_readwrite("ffb_depth", &rbf::GrowerConfig::DepthStage::ffb_depth)
        .def_readwrite("component_connect_ffb_depth_increment",
                       &rbf::GrowerConfig::DepthStage::component_connect_ffb_depth_increment)
        .def_readwrite("component_connect_ffb_max_depth",
                       &rbf::GrowerConfig::DepthStage::component_connect_ffb_max_depth);

    py::class_<rbf::GrowerConfig>(module, "GrowerConfig")
        .def(py::init<>())
        .def_readwrite("mode", &rbf::GrowerConfig::mode)
        .def_readwrite("find_free_box", &rbf::GrowerConfig::find_free_box)
        .def_readwrite("commit_policy", &rbf::GrowerConfig::commit_policy)
        .def_readwrite("max_boxes", &rbf::GrowerConfig::max_boxes)
        .def_readwrite("timeout_ms", &rbf::GrowerConfig::timeout_ms)
        .def_readwrite("max_consecutive_miss", &rbf::GrowerConfig::max_consecutive_miss)
        .def_readwrite("adjacency_tolerance", &rbf::GrowerConfig::adjacency_tolerance)
        .def_readwrite("rng_seed", &rbf::GrowerConfig::rng_seed)
        .def_readwrite("n_threads", &rbf::GrowerConfig::n_threads)
        .def_readwrite("task_batch_size", &rbf::GrowerConfig::task_batch_size)
        .def_readwrite("parallel_threshold", &rbf::GrowerConfig::parallel_threshold)
        .def_readwrite("deterministic_reduce", &rbf::GrowerConfig::deterministic_reduce)
        .def_readwrite("worker_local_ffb", &rbf::GrowerConfig::worker_local_ffb)
        .def_readwrite("rrt_goal_bias", &rbf::GrowerConfig::rrt_goal_bias)
        .def_readwrite("intertree_goal_bias", &rbf::GrowerConfig::intertree_goal_bias)
        .def_readwrite("sustained_goal_bias_cap", &rbf::GrowerConfig::sustained_goal_bias_cap)
        .def_readwrite("high_goal_bias_pulse_period", &rbf::GrowerConfig::high_goal_bias_pulse_period)
        .def_readwrite("rrt_step_ratio", &rbf::GrowerConfig::rrt_step_ratio)
        .def_readwrite("unexplored_sample_prob", &rbf::GrowerConfig::unexplored_sample_prob)
        .def_readwrite("sample_categorical_allocation", &rbf::GrowerConfig::sample_categorical_allocation)
        .def_readwrite("sample_uniform_prob", &rbf::GrowerConfig::sample_uniform_prob)
        .def_readwrite("expand_all_roots_per_sample", &rbf::GrowerConfig::expand_all_roots_per_sample)
        .def_readwrite("extra_random_roots", &rbf::GrowerConfig::extra_random_roots)
        .def_readwrite("random_anchor_targets", &rbf::GrowerConfig::random_anchor_targets)
        .def_readwrite("anchor_target_prob", &rbf::GrowerConfig::anchor_target_prob)
        .def_readwrite("anchor_target_candidate_count", &rbf::GrowerConfig::anchor_target_candidate_count)
        .def_readwrite("anchor_target_max_lca_depth", &rbf::GrowerConfig::anchor_target_max_lca_depth)
        .def_readwrite("anchor_wave_targets_per_batch", &rbf::GrowerConfig::anchor_wave_targets_per_batch)
        .def("set_fixed_anchor_targets", [](rbf::GrowerConfig& config,
                                            const std::vector<std::vector<double>>& anchors) {
            config.fixed_anchor_targets = eigen_vectors_from_lists(anchors);
        })
        .def_readwrite("root_seed_candidate_count", &rbf::GrowerConfig::root_seed_candidate_count)
        .def_readwrite("root_seed_min_normalized_linf", &rbf::GrowerConfig::root_seed_min_normalized_linf)
        .def_readwrite("root_seed_max_lca_depth", &rbf::GrowerConfig::root_seed_max_lca_depth)
        .def_readwrite("root_seed_include_user_seeds", &rbf::GrowerConfig::root_seed_include_user_seeds)
        .def_readwrite("connect_mode", &rbf::GrowerConfig::connect_mode)
        .def_readwrite("component_connect_prob", &rbf::GrowerConfig::component_connect_prob)
        .def_readwrite("component_connect_max_parent_failures", &rbf::GrowerConfig::component_connect_max_parent_failures)
        .def_readwrite("component_connect_candidate_limit", &rbf::GrowerConfig::component_connect_candidate_limit)
        .def_readwrite("component_connect_island_aware", &rbf::GrowerConfig::component_connect_island_aware)
        .def_readwrite("component_connect_frontier_cache", &rbf::GrowerConfig::component_connect_frontier_cache)
        .def_readwrite("component_connect_staged_growth", &rbf::GrowerConfig::component_connect_staged_growth)
        .def_readwrite("component_connect_stage_normalized_linf", &rbf::GrowerConfig::component_connect_stage_normalized_linf)
        .def_readwrite("component_connect_neighbor_root_bias", &rbf::GrowerConfig::component_connect_neighbor_root_bias)
        .def_readwrite("component_connect_neighbor_root_window", &rbf::GrowerConfig::component_connect_neighbor_root_window)
        .def_readwrite("component_connect_lateral_sample_prob", &rbf::GrowerConfig::component_connect_lateral_sample_prob)
        .def_readwrite("component_connect_lateral_sample_attempts", &rbf::GrowerConfig::component_connect_lateral_sample_attempts)
        .def_readwrite("component_connect_require_target_direction", &rbf::GrowerConfig::component_connect_require_target_direction)
        .def_readwrite("component_connect_adaptive_ffb", &rbf::GrowerConfig::component_connect_adaptive_ffb)
        .def_readwrite("component_connect_ffb_depth_increment", &rbf::GrowerConfig::component_connect_ffb_depth_increment)
        .def_readwrite("component_connect_ffb_max_depth", &rbf::GrowerConfig::component_connect_ffb_max_depth)
        .def_readwrite("component_connect_depth_after_unknown_only", &rbf::GrowerConfig::component_connect_depth_after_unknown_only)
        .def_readwrite("component_connect_chain_steps", &rbf::GrowerConfig::component_connect_chain_steps)
        .def_readwrite("component_connect_chain_max_boxes", &rbf::GrowerConfig::component_connect_chain_max_boxes)
        .def_readwrite("frontier_face_memory", &rbf::GrowerConfig::frontier_face_memory)
        .def_readwrite("frontier_face_bins_per_dim", &rbf::GrowerConfig::frontier_face_bins_per_dim)
        .def_readwrite("frontier_face_min_attempts", &rbf::GrowerConfig::frontier_face_min_attempts)
        .def_readwrite("frontier_face_max_attempts", &rbf::GrowerConfig::frontier_face_max_attempts)
        .def_readwrite("frontier_face_area_attempt_scale", &rbf::GrowerConfig::frontier_face_area_attempt_scale)
        .def_readwrite("frontier_face_candidate_limit", &rbf::GrowerConfig::frontier_face_candidate_limit)
        .def_readwrite("frontwave_bootstrap_boxes", &rbf::GrowerConfig::frontwave_bootstrap_boxes)
        .def_readwrite("frontwave_bootstrap_depth", &rbf::GrowerConfig::frontwave_bootstrap_depth)
        .def_readwrite("frontwave_bootstrap_boundary_samples", &rbf::GrowerConfig::frontwave_bootstrap_boundary_samples)
        .def_readwrite("stop_after_connect", &rbf::GrowerConfig::stop_after_connect)
        .def_readwrite("post_connect_extra_boxes", &rbf::GrowerConfig::post_connect_extra_boxes)
        .def_readwrite("quality_min_connected_boxes", &rbf::GrowerConfig::quality_min_connected_boxes)
        .def_readwrite("post_connect_time_budget_ms", &rbf::GrowerConfig::post_connect_time_budget_ms)
        .def_readwrite("depth_stages", &rbf::GrowerConfig::depth_stages)
        .def_readwrite("failure_cooling_enabled", &rbf::GrowerConfig::failure_cooling_enabled)
        .def_readwrite("failure_cooling_threshold", &rbf::GrowerConfig::failure_cooling_threshold)
        .def_readwrite("failure_cooling_box_horizon", &rbf::GrowerConfig::failure_cooling_box_horizon)
        .def_readwrite("failure_cooling_min_depth", &rbf::GrowerConfig::failure_cooling_min_depth)
        .def_readwrite("failure_cooling_unknown_only", &rbf::GrowerConfig::failure_cooling_unknown_only)
        .def_readwrite("failure_cooling_retry_on_depth_raise", &rbf::GrowerConfig::failure_cooling_retry_on_depth_raise)
        .def_readwrite("coverage_first_stop_loss", &rbf::GrowerConfig::coverage_first_stop_loss)
        .def_readwrite("hard_frontier_failure_threshold", &rbf::GrowerConfig::hard_frontier_failure_threshold)
        .def_readwrite("hard_frontier_box_horizon", &rbf::GrowerConfig::hard_frontier_box_horizon)
        .def_readwrite("boundary_epsilon", &rbf::GrowerConfig::boundary_epsilon)
        .def_readwrite("n_boundary_samples", &rbf::GrowerConfig::n_boundary_samples)
        .def_readwrite("trace_enabled", &rbf::GrowerConfig::trace_enabled)
        .def_readwrite("trace_path", &rbf::GrowerConfig::trace_path)
        .def_readwrite("trace_max_events", &rbf::GrowerConfig::trace_max_events)
        .def_readwrite("trace_face_candidate_limit", &rbf::GrowerConfig::trace_face_candidate_limit);

    py::class_<rbf::MergerConfig>(module, "MergerConfig")
        .def(py::init<>())
        .def_readwrite("exact_face_merge", &rbf::MergerConfig::exact_face_merge)
        .def_readwrite("greedy_hull_merge", &rbf::MergerConfig::greedy_hull_merge)
        .def_readwrite("containment_prune", &rbf::MergerConfig::containment_prune)
        .def_readwrite("max_rounds", &rbf::MergerConfig::max_rounds)
        .def_readwrite("target_boxes", &rbf::MergerConfig::target_boxes)
        .def_readwrite("n_threads", &rbf::MergerConfig::n_threads)
        .def_readwrite("candidate_batch_size", &rbf::MergerConfig::candidate_batch_size)
        .def_readwrite("parallel_threshold", &rbf::MergerConfig::parallel_threshold)
        .def_readwrite("deterministic_reduce", &rbf::MergerConfig::deterministic_reduce)
        .def_readwrite("adjacency_tolerance", &rbf::MergerConfig::adjacency_tolerance)
        .def_readwrite("score_threshold", &rbf::MergerConfig::score_threshold);

    py::class_<rbf::RRTConnectConfig>(module, "RRTConnectConfig")
        .def(py::init<>())
        .def_readwrite("max_iters", &rbf::RRTConnectConfig::max_iters)
        .def_readwrite("step_size", &rbf::RRTConnectConfig::step_size)
        .def_readwrite("goal_bias", &rbf::RRTConnectConfig::goal_bias)
        .def_readwrite("timeout_ms", &rbf::RRTConnectConfig::timeout_ms)
        .def_readwrite("segment_resolution", &rbf::RRTConnectConfig::segment_resolution)
        .def_readwrite("segment_step", &rbf::RRTConnectConfig::segment_step)
        .def_readwrite("local_sampling_radius", &rbf::RRTConnectConfig::local_sampling_radius)
        .def_readwrite("shortcut_path", &rbf::RRTConnectConfig::shortcut_path)
        .def_readwrite("domain_tolerance", &rbf::RRTConnectConfig::domain_tolerance)
        .def_readwrite("domain_intervals", &rbf::RRTConnectConfig::domain_intervals);

    py::class_<rbf::ChainPaveConfig>(module, "ChainPaveConfig")
        .def(py::init<>())
        .def_readwrite("max_chain", &rbf::ChainPaveConfig::max_chain)
        .def_readwrite("max_steps_per_waypoint", &rbf::ChainPaveConfig::max_steps_per_waypoint)
        .def_readwrite("adjacency_tolerance", &rbf::ChainPaveConfig::adjacency_tolerance)
        .def_readwrite("refine_covered_waypoints", &rbf::ChainPaveConfig::refine_covered_waypoints)
        .def_readwrite("fill_gaps", &rbf::ChainPaveConfig::fill_gaps)
        .def_readwrite("max_gap_fill_depth", &rbf::ChainPaveConfig::max_gap_fill_depth)
        .def_readwrite("gap_fill_min_step", &rbf::ChainPaveConfig::gap_fill_min_step)
        .def_readwrite("gap_fill_sample_step", &rbf::ChainPaveConfig::gap_fill_sample_step)
        .def_readwrite("gap_fill_time_budget_ms", &rbf::ChainPaveConfig::gap_fill_time_budget_ms)
        .def_readwrite("gap_fill_max_ffb_calls", &rbf::ChainPaveConfig::gap_fill_max_ffb_calls)
        .def_readwrite("require_connected_chain", &rbf::ChainPaveConfig::require_connected_chain)
        .def_readwrite("find_free_box", &rbf::ChainPaveConfig::find_free_box)
        .def_readwrite("commit_policy", &rbf::ChainPaveConfig::commit_policy);

    py::class_<rbf::IslandConnectorConfig>(module, "IslandConnectorConfig")
        .def(py::init<>())
        .def_readwrite("rrt", &rbf::IslandConnectorConfig::rrt)
        .def_readwrite("pave", &rbf::IslandConnectorConfig::pave)
        .def_readwrite("enable_birrt", &rbf::IslandConnectorConfig::enable_birrt)
        .def_readwrite("frontier_bridge", &rbf::IslandConnectorConfig::frontier_bridge)
        .def_readwrite("frontier_bridge_adaptive_ffb", &rbf::IslandConnectorConfig::frontier_bridge_adaptive_ffb)
        .def_readwrite("frontier_bridge_gap_stall_iterations", &rbf::IslandConnectorConfig::frontier_bridge_gap_stall_iterations)
        .def_readwrite("frontier_bridge_ffb_depth_increment", &rbf::IslandConnectorConfig::frontier_bridge_ffb_depth_increment)
        .def_readwrite("frontier_bridge_ffb_max_depth", &rbf::IslandConnectorConfig::frontier_bridge_ffb_max_depth)
        .def_readwrite("frontier_bridge_candidate_limit", &rbf::IslandConnectorConfig::frontier_bridge_candidate_limit)
        .def_readwrite("frontier_bridge_boundary_epsilon", &rbf::IslandConnectorConfig::frontier_bridge_boundary_epsilon)
        .def_readwrite("per_pair_timeout_ms", &rbf::IslandConnectorConfig::per_pair_timeout_ms)
        .def_readwrite("point_validated_gap_tolerance", &rbf::IslandConnectorConfig::point_validated_gap_tolerance)
        .def_readwrite("point_validated_gap_resolution", &rbf::IslandConnectorConfig::point_validated_gap_resolution)
        .def_readwrite("max_pairs_per_gap", &rbf::IslandConnectorConfig::max_pairs_per_gap)
        .def_readwrite("max_total_bridge_boxes", &rbf::IslandConnectorConfig::max_total_bridge_boxes)
        .def_readwrite("segment_edges_enabled", &rbf::IslandConnectorConfig::segment_edges_enabled)
        .def_readwrite("rrt_segment_edges", &rbf::IslandConnectorConfig::rrt_segment_edges)
        .def_readwrite("point_gap_segment_edges", &rbf::IslandConnectorConfig::point_gap_segment_edges)
        .def_readwrite("segment_edges_fallback_only", &rbf::IslandConnectorConfig::segment_edges_fallback_only)
        .def_readwrite("point_validated_gap_step", &rbf::IslandConnectorConfig::point_validated_gap_step)
        .def_readwrite("n_threads", &rbf::IslandConnectorConfig::n_threads)
        .def_readwrite("pair_batch_size", &rbf::IslandConnectorConfig::pair_batch_size)
        .def_readwrite("parallel_threshold", &rbf::IslandConnectorConfig::parallel_threshold)
        .def_readwrite("deterministic_reduce", &rbf::IslandConnectorConfig::deterministic_reduce);

    py::enum_<rbf::lect_database::SplitStrategy>(module, "SplitStrategy")
        .value("RoundRobin", rbf::lect_database::SplitStrategy::RoundRobin)
        .value("WidestRoot", rbf::lect_database::SplitStrategy::WidestRoot)
        .value("AAFKVolumeMin", rbf::lect_database::SplitStrategy::AAFKVolumeMin);

    py::class_<rbf::lect_database::SplitPolicyDescriptor>(module, "SplitPolicyDescriptor")
        .def(py::init<>())
        .def_readwrite("strategy", &rbf::lect_database::SplitPolicyDescriptor::strategy)
        .def_readwrite("min_width", &rbf::lect_database::SplitPolicyDescriptor::min_width)
        .def_readwrite("midpoint", &rbf::lect_database::SplitPolicyDescriptor::midpoint)
        .def_readwrite("deterministic_tie_break", &rbf::lect_database::SplitPolicyDescriptor::deterministic_tie_break)
        .def_readwrite("dimension_schedule_hash", &rbf::lect_database::SplitPolicyDescriptor::dimension_schedule_hash)
        .def_readwrite("depth_dimensions", &rbf::lect_database::SplitPolicyDescriptor::depth_dimensions);

    module.def("split_policy_descriptor", &rbf::lect_database::split_policy_descriptor, py::arg("descriptor"));
    module.def("split_policy_hash", &rbf::lect_database::split_policy_hash, py::arg("descriptor"));
    module.def("stable_hash",
        [](const std::string& text) {
            return rbf::lect_database::stable_hash(text);
        },
        py::arg("text"));

    py::class_<rbf::lect_database::OnlineEnvelopeCacheConfig>(module, "OnlineEnvelopeCacheConfig")
        .def(py::init<>())
        .def_readwrite("max_nodes", &rbf::lect_database::OnlineEnvelopeCacheConfig::max_nodes)
        .def_readwrite("max_payload_bytes", &rbf::lect_database::OnlineEnvelopeCacheConfig::max_payload_bytes)
        .def_readwrite("allow_database_backfill", &rbf::lect_database::OnlineEnvelopeCacheConfig::allow_database_backfill);

    py::class_<rbf::LectDatabaseRuntimeConfig>(module, "LectDatabaseRuntimeConfig")
        .def(py::init<>())
        .def_property("path",
            [](const rbf::LectDatabaseRuntimeConfig& config) { return config.path.string(); },
            [](rbf::LectDatabaseRuntimeConfig& config, const std::string& path) { config.path = path; })
        .def_property("external_evidence_path",
            [](const rbf::LectDatabaseRuntimeConfig& config) { return config.external_evidence_path.string(); },
            [](rbf::LectDatabaseRuntimeConfig& config, const std::string& path) { config.external_evidence_path = path; })
        .def_property("external_evidence_snapshot_path",
            [](const rbf::LectDatabaseRuntimeConfig& config) { return config.external_evidence_snapshot_path.string(); },
            [](rbf::LectDatabaseRuntimeConfig& config, const std::string& path) { config.external_evidence_snapshot_path = path; })
        .def_readwrite("root_intervals_override", &rbf::LectDatabaseRuntimeConfig::root_intervals_override)
        .def_readwrite("coverage_intervals_override", &rbf::LectDatabaseRuntimeConfig::coverage_intervals_override)
        .def_readwrite("split_policy", &rbf::LectDatabaseRuntimeConfig::split_policy)
        .def_readwrite("online_cache", &rbf::LectDatabaseRuntimeConfig::online_cache)
        .def_readwrite("external_evidence_use_snapshot", &rbf::LectDatabaseRuntimeConfig::external_evidence_use_snapshot)
        .def_readwrite("external_evidence_auto_build_snapshot", &rbf::LectDatabaseRuntimeConfig::external_evidence_auto_build_snapshot)
        .def_readwrite("read_only", &rbf::LectDatabaseRuntimeConfig::read_only)
        .def_readwrite("create_if_missing", &rbf::LectDatabaseRuntimeConfig::create_if_missing)
        .def_readwrite("verify_identity", &rbf::LectDatabaseRuntimeConfig::verify_identity)
        .def_readwrite("replay_journal", &rbf::LectDatabaseRuntimeConfig::replay_journal)
        .def_readwrite("propagate_parent_hulls", &rbf::LectDatabaseRuntimeConfig::propagate_parent_hulls)
        .def_readwrite("defer_parent_hull_writes", &rbf::LectDatabaseRuntimeConfig::defer_parent_hull_writes)
        .def_readwrite("canonical_mode", &rbf::LectDatabaseRuntimeConfig::canonical_mode)
        .def_readwrite("checkpoint_after_build", &rbf::LectDatabaseRuntimeConfig::checkpoint_after_build)
        .def_readwrite("symmetry_descriptor", &rbf::LectDatabaseRuntimeConfig::symmetry_descriptor)
        .def_readwrite("page_size_bytes", &rbf::LectDatabaseRuntimeConfig::page_size_bytes)
        .def_readwrite("max_resident_pages", &rbf::LectDatabaseRuntimeConfig::max_resident_pages)
        .def_readwrite("max_tree_depth", &rbf::LectDatabaseRuntimeConfig::max_tree_depth);

    py::class_<rbf::QueryConfig>(module, "QueryConfig")
        .def(py::init<>())
        .def_readwrite("nearest_if_outside", &rbf::QueryConfig::nearest_if_outside)
        .def_readwrite("shortcut_boxes", &rbf::QueryConfig::shortcut_boxes)
        .def_readwrite("shortcut_cost_aware", &rbf::QueryConfig::shortcut_cost_aware)
        .def_readwrite("shortcut_cost_factor", &rbf::QueryConfig::shortcut_cost_factor)
        .def_readwrite("collision_shortcut", &rbf::QueryConfig::collision_shortcut)
        .def_readwrite("collision_shortcut_resolution", &rbf::QueryConfig::collision_shortcut_resolution)
        .def_readwrite("strict_path_audit", &rbf::QueryConfig::strict_path_audit)
        .def_readwrite("audit_resolution", &rbf::QueryConfig::audit_resolution)
        .def_readwrite("audit_segment_step", &rbf::QueryConfig::audit_segment_step)
        .def_readwrite("audit_collision_tolerance", &rbf::QueryConfig::audit_collision_tolerance)
        .def_readwrite("repair_on_audit_failure", &rbf::QueryConfig::repair_on_audit_failure)
        .def_readwrite("repair_max_attempts", &rbf::QueryConfig::repair_max_attempts)
        .def_readwrite("repair_rrt_max_iters", &rbf::QueryConfig::repair_rrt_max_iters)
        .def_readwrite("repair_timeout_ms", &rbf::QueryConfig::repair_timeout_ms)
        .def_readwrite("repair_local_sampling_radius", &rbf::QueryConfig::repair_local_sampling_radius)
        .def_readwrite("repair_local_sampling_growth", &rbf::QueryConfig::repair_local_sampling_growth)
        .def_readwrite("final_rrt_simplify", &rbf::QueryConfig::final_rrt_simplify)
        .def_readwrite("final_rrt_simplify_timeout_ms", &rbf::QueryConfig::final_rrt_simplify_timeout_ms)
        .def_readwrite("final_rrt_simplify_max_iters", &rbf::QueryConfig::final_rrt_simplify_max_iters)
        .def_readwrite("final_rrt_simplify_attempts", &rbf::QueryConfig::final_rrt_simplify_attempts)
        .def_readwrite("adjacency_tolerance", &rbf::QueryConfig::adjacency_tolerance);

    py::class_<rbf::RBFPlanningConfig>(module, "RBFPlanningConfig")
        .def(py::init<>())
        .def_readwrite("grower", &rbf::RBFPlanningConfig::grower)
        .def_readwrite("merger", &rbf::RBFPlanningConfig::merger)
        .def_readwrite("connector", &rbf::RBFPlanningConfig::connector)
        .def_readwrite("query", &rbf::RBFPlanningConfig::query)
        .def_readwrite("endpoint_source", &rbf::RBFPlanningConfig::endpoint_source)
        .def_readwrite("envelope_type", &rbf::RBFPlanningConfig::envelope_type)
        .def_readwrite("validation", &rbf::RBFPlanningConfig::validation)
        .def_readwrite("database", &rbf::RBFPlanningConfig::database)
        .def_readwrite("runtime", &rbf::RBFPlanningConfig::runtime)
        .def_readwrite("dynamic_update", &rbf::RBFPlanningConfig::dynamic_update)
        .def_readwrite("enable_merger", &rbf::RBFPlanningConfig::enable_merger)
        .def_readwrite("enable_connector", &rbf::RBFPlanningConfig::enable_connector)
        .def_readwrite("query_bridge_pave_depth", &rbf::RBFPlanningConfig::query_bridge_pave_depth)
        .def_readwrite("query_bridge_ffb_start_depth", &rbf::RBFPlanningConfig::query_bridge_ffb_start_depth)
        .def_readwrite("query_endpoint_anchor_ffb_depth", &rbf::RBFPlanningConfig::query_endpoint_anchor_ffb_depth)
        .def_readwrite("query_endpoint_anchor_ffb_depths", &rbf::RBFPlanningConfig::query_endpoint_anchor_ffb_depths)
        .def_readwrite("query_endpoint_point_anchor", &rbf::RBFPlanningConfig::query_endpoint_point_anchor)
        .def_readwrite("endpoint_shortlink_max_length", &rbf::RBFPlanningConfig::endpoint_shortlink_max_length)
        .def_readwrite("query_bridge_accept_segment_fraction", &rbf::RBFPlanningConfig::query_bridge_accept_segment_fraction)
        .def_readwrite("query_bridge_accept_path_ratio", &rbf::RBFPlanningConfig::query_bridge_accept_path_ratio)
        .def_readwrite("query_bridge_accept_path_additive", &rbf::RBFPlanningConfig::query_bridge_accept_path_additive)
        .def_readwrite("query_bridge_accept_max_path_length", &rbf::RBFPlanningConfig::query_bridge_accept_max_path_length)
        .def_readwrite("query_bridge_no_path_retry_attempts", &rbf::RBFPlanningConfig::query_bridge_no_path_retry_attempts)
        .def_readwrite("query_bridge_no_path_retry_stop_on_first_success", &rbf::RBFPlanningConfig::query_bridge_no_path_retry_stop_on_first_success)
        .def_readwrite("query_bridge_forced_attempts", &rbf::RBFPlanningConfig::query_bridge_forced_attempts)
        .def_readwrite("query_bridge_attempt_offset", &rbf::RBFPlanningConfig::query_bridge_attempt_offset)
        .def_readwrite("query_bridge_rrt_fixed_iters", &rbf::RBFPlanningConfig::query_bridge_rrt_fixed_iters)
        .def_readwrite("query_bridge_local_radius_schedule", &rbf::RBFPlanningConfig::query_bridge_local_radius_schedule)
        .def_readwrite("query_bridge_no_path_retry_budget_iters", &rbf::RBFPlanningConfig::query_bridge_no_path_retry_budget_iters)
        .def_readwrite("query_bridge_no_path_retry_budget_attempts", &rbf::RBFPlanningConfig::query_bridge_no_path_retry_budget_attempts)
        .def_readwrite("query_bridge_hybridize_attempt_paths", &rbf::RBFPlanningConfig::query_bridge_hybridize_attempt_paths)
        .def_readwrite("query_bridge_hybrid_max_paths", &rbf::RBFPlanningConfig::query_bridge_hybrid_max_paths)
        .def_readwrite("query_bridge_hybrid_max_vertices", &rbf::RBFPlanningConfig::query_bridge_hybrid_max_vertices)
        .def_readwrite("query_bridge_hybrid_max_cross_checks", &rbf::RBFPlanningConfig::query_bridge_hybrid_max_cross_checks)
        .def_readwrite("query_bridge_parallel_rrt_early_stop", &rbf::RBFPlanningConfig::query_bridge_parallel_rrt_early_stop)
        .def_readwrite("query_bridge_parallel_rrt_early_stop_min_successes", &rbf::RBFPlanningConfig::query_bridge_parallel_rrt_early_stop_min_successes)
        .def_readwrite("query_bridge_parallel_rrt_early_stop_ratio", &rbf::RBFPlanningConfig::query_bridge_parallel_rrt_early_stop_ratio)
        .def_readwrite("query_bridge_parallel_rrt_early_stop_additive", &rbf::RBFPlanningConfig::query_bridge_parallel_rrt_early_stop_additive)
        .def_readwrite("query_bridge_scene_reusable_edges", &rbf::RBFPlanningConfig::query_bridge_scene_reusable_edges)
        .def_readwrite("query_bridge_direct_segment_after_rrt", &rbf::RBFPlanningConfig::query_bridge_direct_segment_after_rrt)
        .def_readwrite("query_bridge_fast_direct_segment_after_rrt", &rbf::RBFPlanningConfig::query_bridge_fast_direct_segment_after_rrt)
        .def_readwrite("query_bridge_fast_direct_random_shortcut_iters", &rbf::RBFPlanningConfig::query_bridge_fast_direct_random_shortcut_iters)
        .def_readwrite("query_bridge_direct_max_length", &rbf::RBFPlanningConfig::query_bridge_direct_max_length)
        .def_readwrite("query_bridge_direct_sample_step", &rbf::RBFPlanningConfig::query_bridge_direct_sample_step)
        .def_readwrite("query_bridge_direct_sample_steps_by_query", &rbf::RBFPlanningConfig::query_bridge_direct_sample_steps_by_query)
        .def_readwrite("query_bridge_full_residual_overlay_when_connected", &rbf::RBFPlanningConfig::query_bridge_full_residual_overlay_when_connected)
        .def_readwrite("query_bridge_adaptive_max_repair_subdivisions", &rbf::RBFPlanningConfig::query_bridge_adaptive_max_repair_subdivisions)
        .def_readwrite("query_bridge_adaptive_fine_step", &rbf::RBFPlanningConfig::query_bridge_adaptive_fine_step)
        .def_readwrite("query_bridge_adaptive_max_repair_calls", &rbf::RBFPlanningConfig::query_bridge_adaptive_max_repair_calls)
        .def_readwrite("query_bridge_adaptive_max_repair_calls_by_query", &rbf::RBFPlanningConfig::query_bridge_adaptive_max_repair_calls_by_query)
        .def_readwrite("query_box_transition_edge_cost_penalty", &rbf::RBFPlanningConfig::query_box_transition_edge_cost_penalty)
        .def_readwrite("query_box_transition_nonprogress_penalty", &rbf::RBFPlanningConfig::query_box_transition_nonprogress_penalty)
        .def_readwrite("query_box_transition_line_deviation_penalty", &rbf::RBFPlanningConfig::query_box_transition_line_deviation_penalty)
        .def_readwrite("query_bridge_edge_cost_penalty", &rbf::RBFPlanningConfig::query_bridge_edge_cost_penalty)
        .def_readwrite("query_foreign_edge_cost_penalty", &rbf::RBFPlanningConfig::query_foreign_edge_cost_penalty)
        .def_readwrite("portal_membership_policy", &rbf::RBFPlanningConfig::portal_membership_policy);

    py::class_<rbf::RBFQueryRuntimeOptions>(module, "RBFQueryRuntimeOptions")
        .def(py::init<>())
        .def_readwrite("active_query_index", &rbf::RBFQueryRuntimeOptions::active_query_index);

    py::class_<rbf::BuildProfile>(module, "BuildProfile")
        .def_readonly("total_ms", &rbf::BuildProfile::total_ms)
        .def_readonly("grow_ms", &rbf::BuildProfile::grow_ms)
        .def_readonly("merge_ms", &rbf::BuildProfile::merge_ms)
        .def_readonly("connector_ms", &rbf::BuildProfile::connector_ms)
        .def_readonly("adjacency_ms", &rbf::BuildProfile::adjacency_ms)
        .def_readonly("raw_boxes", &rbf::BuildProfile::raw_boxes)
        .def_readonly("final_boxes", &rbf::BuildProfile::final_boxes)
        .def_readonly("grow_adjacency_islands", &rbf::BuildProfile::grow_adjacency_islands)
        .def_readonly("grow_largest_island", &rbf::BuildProfile::grow_largest_island)
        .def_readonly("bridge_boxes_added", &rbf::BuildProfile::bridge_boxes_added)
        .def_readonly("segment_edges", &rbf::BuildProfile::segment_edges)
        .def_readonly("segment_edges_added", &rbf::BuildProfile::segment_edges_added)
        .def_readonly("rrt_segment_edges_added", &rbf::BuildProfile::rrt_segment_edges_added)
        .def_readonly("point_gap_segment_edges_added", &rbf::BuildProfile::point_gap_segment_edges_added)
        .def_readonly("connector_attempted_pairs", &rbf::BuildProfile::connector_attempted_pairs)
        .def_readonly("connector_connected", &rbf::BuildProfile::connector_connected)
        .def_readonly("adjacency_islands", &rbf::BuildProfile::adjacency_islands)
        .def_readonly("diagnostics", &rbf::BuildProfile::diagnostics);

    py::class_<rbf::RebuildProfile>(module, "RebuildProfile")
        .def_readonly("boxes_before", &rbf::RebuildProfile::boxes_before)
        .def_readonly("boxes_after", &rbf::RebuildProfile::boxes_after)
        .def_readonly("boxes_removed", &rbf::RebuildProfile::boxes_removed)
        .def_readonly("raw_boxes_before", &rbf::RebuildProfile::raw_boxes_before)
        .def_readonly("raw_boxes_after", &rbf::RebuildProfile::raw_boxes_after)
        .def_readonly("raw_boxes_removed", &rbf::RebuildProfile::raw_boxes_removed)
        .def_readonly("adjacency_islands", &rbf::RebuildProfile::adjacency_islands)
        .def_readonly("obstacles_before", &rbf::RebuildProfile::obstacles_before)
        .def_readonly("obstacles_after", &rbf::RebuildProfile::obstacles_after)
        .def_readonly("removed_obstacle_index", &rbf::RebuildProfile::removed_obstacle_index)
        .def_readonly("dirty_boxes", &rbf::RebuildProfile::dirty_boxes)
        .def_readonly("dirty_boxes_used", &rbf::RebuildProfile::dirty_boxes_used)
        .def_readonly("dirty_seed_count", &rbf::RebuildProfile::dirty_seed_count)
        .def_readonly("regrow_attempts", &rbf::RebuildProfile::regrow_attempts)
        .def_readonly("boxes_added", &rbf::RebuildProfile::boxes_added)
        .def_readonly("raw_boxes_added", &rbf::RebuildProfile::raw_boxes_added)
        .def_readonly("bridge_boxes_added", &rbf::RebuildProfile::bridge_boxes_added)
        .def_readonly("segment_edges_added", &rbf::RebuildProfile::segment_edges_added)
        .def_readonly("rrt_segment_edges_added", &rbf::RebuildProfile::rrt_segment_edges_added)
        .def_readonly("point_gap_segment_edges_added", &rbf::RebuildProfile::point_gap_segment_edges_added)
        .def_readonly("collision_cache_boxes_before", &rbf::RebuildProfile::collision_cache_boxes_before)
        .def_readonly("collision_cache_boxes_after", &rbf::RebuildProfile::collision_cache_boxes_after)
        .def_readonly("collision_cache_candidates", &rbf::RebuildProfile::collision_cache_candidates)
        .def_readonly("collision_cache_promoted", &rbf::RebuildProfile::collision_cache_promoted)
        .def_readonly("collision_cache_rejected_collision", &rbf::RebuildProfile::collision_cache_rejected_collision)
        .def_readonly("collision_cache_rejected_contained", &rbf::RebuildProfile::collision_cache_rejected_contained)
        .def_readonly("collision_cache_rejected_disconnected", &rbf::RebuildProfile::collision_cache_rejected_disconnected)
        .def_readonly("used_spatial_dirty_region", &rbf::RebuildProfile::used_spatial_dirty_region)
        .def_readonly("used_warm_rebuild", &rbf::RebuildProfile::used_warm_rebuild)
        .def_readonly("fallback_reason", &rbf::RebuildProfile::fallback_reason)
        .def_readonly("dirty_region_ms", &rbf::RebuildProfile::dirty_region_ms)
        .def_readonly("regrow_ms", &rbf::RebuildProfile::regrow_ms)
        .def_readonly("warm_rebuild_ms", &rbf::RebuildProfile::warm_rebuild_ms)
        .def_readonly("collision_check_ms", &rbf::RebuildProfile::collision_check_ms)
        .def_readonly("adjacency_ms", &rbf::RebuildProfile::adjacency_ms)
        .def_readonly("total_ms", &rbf::RebuildProfile::total_ms)
        .def_readonly("diagnostics", &rbf::RebuildProfile::diagnostics);

    py::class_<rbf::QueryResult>(module, "QueryResult")
        .def_readonly("success", &rbf::QueryResult::success)
        .def_readonly("start_box_id", &rbf::QueryResult::start_box_id)
        .def_readonly("goal_box_id", &rbf::QueryResult::goal_box_id)
        .def_readonly("box_sequence", &rbf::QueryResult::box_sequence)
        .def_readonly("segment_edge_sequence", &rbf::QueryResult::segment_edge_sequence)
        .def_readonly("path", &rbf::QueryResult::path)
        .def("path_as_lists", [](const rbf::QueryResult& result) {
            return eigen_path_to_lists(result.path);
        })
        .def_readonly("path_length", &rbf::QueryResult::path_length)
        .def_readonly("raw_path_length", &rbf::QueryResult::raw_path_length)
        .def_readonly("query_time_ms", &rbf::QueryResult::query_time_ms)
        .def_readonly("segment_edges_used", &rbf::QueryResult::segment_edges_used)
        .def_readonly("audit_status", &rbf::QueryResult::audit_status)
        .def_readonly("audit_passed", &rbf::QueryResult::audit_passed)
        .def_readonly("audit_time_ms", &rbf::QueryResult::audit_time_ms)
        .def_readonly("repair_time_ms", &rbf::QueryResult::repair_time_ms)
        .def_readonly("final_simplify_time_ms", &rbf::QueryResult::final_simplify_time_ms)
        .def_readonly("repair_count", &rbf::QueryResult::repair_count)
        .def_readonly("failed_segment_index", &rbf::QueryResult::failed_segment_index)
        .def_readonly("certified_box_length", &rbf::QueryResult::certified_box_length)
        .def_readonly("provisional_audited_length", &rbf::QueryResult::provisional_audited_length)
        .def_readonly("segment_edge_length", &rbf::QueryResult::segment_edge_length)
        .def_readonly("obb_edges_used", &rbf::QueryResult::obb_edges_used)
        .def_readonly("obb_regions_used", &rbf::QueryResult::obb_regions_used)
        .def_readonly("obb_edge_length", &rbf::QueryResult::obb_edge_length)
        .def_readonly("partition_cells_used", &rbf::QueryResult::partition_cells_used)
        .def_readonly("partition_search_ms", &rbf::QueryResult::partition_search_ms)
        .def_readonly("partition_repair_ms", &rbf::QueryResult::partition_repair_ms)
        .def_readonly("non_grid_cells_used", &rbf::QueryResult::non_grid_cells_used)
        .def_readonly("residual_segment_fraction", &rbf::QueryResult::residual_segment_fraction)
        .def_readonly("remaining_unsafe_assumptions", &rbf::QueryResult::remaining_unsafe_assumptions);
}

}  // namespace rbf::python_binding
